spring.application.name=SecurityDemo

spring.security.user.name=user
spring.security.user.password=telusko

spring.datasource.url=jdbc:postgresql://localhost:5437/telusko
spring.datasource.username=root
spring.datasource.password=root

spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false
